blank_issues_enabled: false
contact_links:
  - name: 💬 Discussões
    url: https://github.com/seu-usuario/aluguel-facil/discussions
    about: Para dúvidas gerais, use as Discussões
  - name: 📖 Documentação
    url: https://github.com/seu-usuario/aluguel-facil/wiki
    about: Confira a documentação completa